# Generated by Django 2.2.2 on 2019-07-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='album',
        ),
        migrations.AddField(
            model_name='artist',
            name='album',
            field=models.ManyToManyField(to='music.Album'),
        ),
        migrations.RemoveField(
            model_name='artist',
            name='song',
        ),
        migrations.AddField(
            model_name='artist',
            name='song',
            field=models.ManyToManyField(to='music.Song'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='music.Album'),
        ),
    ]
